version: '3'

services:
  potential-crud-db:
    container_name: potential-crud-db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password

  potential-crud-api-builder:
    container_name: potential-crud-api-builder
    image: potential-crud-api-builder
    build:
      context: ./developers/
      dockerfile: Dockerfile.builder
    env_file:
      - ./developers/.env
    environment:
      DB_HOST: potential-crud-db
      DB_PORT: 3306
    command: ./wait-for-it.sh potential-crud-db:3306 --timeout=5000 -- npm run bootstrap
    depends_on:
      - potential-crud-db

  potential-crud-api:
    container_name: potential-crud-api
    build: ./developers
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./developers/.env
    environment:
      NODE_ENV: production
      DB_PORT: 3306
      DB_HOST: potential-crud-db
    depends_on:
      - potential-crud-api-builder
